# Copyright (C) 2026 Dione Bastos
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


from typing import Literal
from uuid import UUID

from pydantic import BaseModel, Field, PrivateAttr, model_validator


class BusinessRuleSchema(BaseModel):
    """LLM output schema. Warnings are never included here — they are
    generated by the application via @model_validator, not by Gemini."""

    client_name: str = Field(
        ...,
        max_length=255,
        description="Name of the company or person requesting the project",
    )
    core_objective: str = Field(
        ...,
        description=("The 'north star' of the project — the main problem it solves"),
    )
    technical_constraints: list[str] = Field(
        default_factory=list,
        description=(
            "Mandatory technologies, deadlines, or infrastructure limitations"
        ),
    )
    acceptance_criteria: list[str] = Field(
        default_factory=list,
        description=(
            "What needs to be working for the project to be considered delivered"
        ),
    )
    additional_notes: str | None = Field(
        None,
        description=("Relevant information that doesn't fit the previous fields"),
    )
    confidence_level: Literal["HIGH", "MEDIUM", "LOW"] = Field(
        ...,
        description=(
            "Confidence degree in the extraction given the noise level of the text"
        ),
    )

    # Internal field — not populated by the LLM
    _warnings: list[str] = PrivateAttr(default_factory=list)

    @model_validator(mode="after")
    def generate_warnings(self) -> "BusinessRuleSchema":
        """Generate application-side warnings based on data quality."""
        warnings: list[str] = []
        if not self.technical_constraints:
            warnings.append("Technical constraints not detected in the raw text")
        if not self.acceptance_criteria:
            warnings.append("Acceptance criteria not detected in the raw text")
        if self.confidence_level == "LOW":
            warnings.append(
                "LOW confidence in the extraction "
                "— review the original text before proceeding"
            )
        if self.confidence_level == "MEDIUM" and not self.acceptance_criteria:
            warnings.append(
                "MEDIUM confidence with missing acceptance criteria "
                "— high risk ingestion"
            )
        self._warnings = warnings
        return self

    @property
    def warnings(self) -> list[str]:
        """Return the list of application-generated warnings."""
        return self._warnings


class IngestBusinessRequest(BaseModel):
    """Request schema for business rule ingestion."""

    raw_text: str = Field(
        ...,
        min_length=20,
        max_length=50000,
        description="Raw text from the meeting note or transcript",
    )
    project_id: UUID = Field(
        ...,
        description="UUID of the project this business rule belongs to",
    )
    source: str | None = Field(
        None,
        description="Source filename or URL",
    )


class IngestBusinessResponse(BaseModel):
    """Response schema for business rule ingestion."""

    record_id: str
    data: BusinessRuleSchema
    warnings: list[str]
    saved_in_db: bool
