"""Cookbook recipe models

Revision ID: 756b12e9d829
Revises: a1b2c3d4e5f6
Create Date: 2026-03-20 18:07:19.006558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '756b12e9d829'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cookbook_recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('prerequisites', sa.Text(), nullable=True),
    sa.Column('steps', sa.Text(), nullable=False),
    sa.Column('code_snippets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_graph_edges_project_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_source_node_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_target_node_id'), table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index(op.f('ix_graph_nodes_community_id'), table_name='graph_nodes')
    op.drop_index(op.f('ix_graph_nodes_embedding_hnsw'), table_name='graph_nodes', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_graph_nodes_project_id'), table_name='graph_nodes')
    op.drop_table('graph_nodes')
    op.drop_table('business_rules')
    op.drop_table('plans')
    op.add_column('knowledge_documents', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('knowledge_documents', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('knowledge_documents', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    op.drop_column('knowledge_documents', 'metadata_json')
    op.drop_column('knowledge_documents', 'raw_content')
    op.drop_column('knowledge_documents', 'cache_expires_at')
    op.drop_column('knowledge_documents', 'gemini_file_uri')
    op.drop_column('knowledge_documents', 'gemini_cache_name')
    op.drop_column('projects', 'llm_model')
    op.drop_column('projects', 'config_json')
    op.drop_column('projects', 'namespace')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('namespace', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('llm_model', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('knowledge_documents', sa.Column('gemini_cache_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('knowledge_documents', sa.Column('gemini_file_uri', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('knowledge_documents', sa.Column('cache_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('knowledge_documents', sa.Column('raw_content', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('knowledge_documents', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('knowledge_documents', 'embedding')
    op.drop_column('knowledge_documents', 'error_message')
    op.drop_column('knowledge_documents', 'content')
    op.create_table('plans',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('markdown_body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('risks_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('approval_justification', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('plans_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('plans_pkey'))
    )
    op.create_table('business_rules',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('client_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('core_objective', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('technical_constraints', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('acceptance_criteria', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('additional_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confidence_level', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('namespace', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('business_rules_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('business_rules_pkey'))
    )
    op.create_table('graph_nodes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), autoincrement=False, nullable=True, comment='pgvector Vector(768) — see raw SQL index below'),
    sa.Column('source_document_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('community_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_valid', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('graph_nodes_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('graph_nodes_pkey')),
    sa.UniqueConstraint('project_id', 'name', name=op.f('uq_graph_nodes_project_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_graph_nodes_project_id'), 'graph_nodes', ['project_id'], unique=False)
    op.create_index(op.f('ix_graph_nodes_embedding_hnsw'), 'graph_nodes', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_graph_nodes_community_id'), 'graph_nodes', ['community_id'], unique=False)
    op.create_table('graph_edges',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_node_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_node_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('relation_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('1.0'), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.VARCHAR(length=10), server_default=sa.text("'MEDIUM'::character varying"), autoincrement=False, nullable=False),
    sa.Column('source_document_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_valid', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('graph_edges_project_id_fkey')),
    sa.ForeignKeyConstraint(['source_node_id'], ['graph_nodes.id'], name=op.f('graph_edges_source_node_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['graph_nodes.id'], name=op.f('graph_edges_target_node_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('graph_edges_pkey'))
    )
    op.create_index(op.f('ix_graph_edges_target_node_id'), 'graph_edges', ['target_node_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_source_node_id'), 'graph_edges', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_project_id'), 'graph_edges', ['project_id'], unique=False)
    op.drop_table('cookbook_recipes')
    # ### end Alembic commands ###
