"""Prumo CLI — entry point that orchestrates the crawler and exporter.

This is the only module that performs disk I/O. It validates inputs,
shows progress using Rich, and resolves API keys.

Available commands:
  prumo init   → interactive wizard that creates the .env with the required credentials
  prumo fetch  → crawls documentation and generates llms.txt

Fetch operating modes:
  - Default:   static HTTP crawling (httpx + BeautifulSoup)
  - --github:  reads via GitHub Contents API (.md/.mdx), bypasses JS-Wall

Credential resolution order (highest to lowest priority):
  1. CLI flag        (--api-key, --github-token)
  2. .env file       (loaded automatically from the current directory)
  3. Shell env var
  4. Clear error — run `prumo init` to configure
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Annotated

import httpx
import typer
from dotenv import load_dotenv
from rich.console import Console
from rich.panel import Panel
from rich.progress import BarColumn, Progress, SpinnerColumn, TaskProgressColumn, TextColumn

from prumo.crawler import crawl, crawl_github
from prumo.exporter import export_llms_txt

# Loads .env from the directory where the command is executed.
# override=False ensures variables already defined in the shell take precedence.
load_dotenv(dotenv_path=Path.cwd() / ".env", override=False)

app = typer.Typer(
    name="prumo",
    help="Convert documentation sites into llms.txt files for AI agents.",
    add_completion=False,
)
console = Console()

API_KEY_ENV_VARS = {
    "gemini": "GEMINI_API_KEY",
    "claude": "ANTHROPIC_API_KEY",
}


@app.callback()
def _callback() -> None:
    pass


# ---------------------------------------------------------------------------
# Credential resolution helpers
# ---------------------------------------------------------------------------


def _resolve_api_key(provider: str, api_key_flag: str | None) -> str:
    """Resolves the API key: CLI flag → environment variable → error."""
    if api_key_flag:
        return api_key_flag

    env_var = API_KEY_ENV_VARS.get(provider, "")
    env_value = os.environ.get(env_var, "")
    if env_value:
        return env_value

    console.print(
        f"\n[bold red]Error:[/] API key not found for provider '[cyan]{provider}[/cyan]'.\n\n"
        f"  Set it up quickly by running:\n"
        f"    [bold green]prumo init[/bold green]\n\n"
        f"  Or add it manually to [bold].env[/bold]:\n"
        f"    [green]{env_var}=your-key-here[/green]"
    )
    raise typer.Exit(code=1)


def _resolve_github_token(github_token_flag: str | None) -> str:
    """Resolves the GitHub token: CLI flag → GITHUB_TOKEN env var → error."""
    if github_token_flag:
        return github_token_flag

    env_value = os.environ.get("GITHUB_TOKEN", "")
    if env_value:
        return env_value

    console.print(
        "\n[bold red]Error:[/] GitHub token not found.\n\n"
        "  Set it up quickly by running:\n"
        "    [bold green]prumo init[/bold green]\n\n"
        "  Or add it manually to [bold].env[/bold]:\n"
        "    [green]GITHUB_TOKEN=your-token-here[/green]"
    )
    raise typer.Exit(code=1)


def _validate_url(url: str) -> None:
    """Validates that a URL is reachable before crawling."""
    try:
        with httpx.Client(timeout=10) as client:
            response = client.head(url, follow_redirects=True)
            response.raise_for_status()
    except (httpx.HTTPError, httpx.TimeoutException) as exc:
        console.print(f"[bold red]Error:[/] Unreachable URL: {url}")
        console.print(f"  Detail: {exc}")
        raise typer.Exit(code=1) from exc


# ---------------------------------------------------------------------------
# Command: prumo init
# ---------------------------------------------------------------------------


@app.command()
def init(
    force: Annotated[
        bool,
        typer.Option("--force", "-f", help="Overwrite existing .env without prompting"),
    ] = False,
) -> None:
    """Interactively configure Prumo credentials by creating a .env file."""

    env_path = Path.cwd() / ".env"

    console.print()
    console.print(Panel(
        "[bold cyan]Prumo[/bold cyan] — Initial setup\n\n"
        "This wizard will create a [bold].env[/bold] file with your credentials.\n"
        "Keys are stored [bold]locally[/bold] and never leave your machine.",
        expand=False,
    ))
    console.print()

    # Warn if .env already exists
    if env_path.exists() and not force:
        overwrite = typer.confirm(
            f"  A .env file already exists at {env_path}. Overwrite it?",
            default=False,
        )
        if not overwrite:
            console.print("\n[yellow]Cancelled.[/yellow] Use [bold]--force[/bold] to overwrite without confirmation.\n")
            raise typer.Exit()
        console.print()

    lines: list[str] = ["# Prumo — credentials\n# Generated by `prumo init`\n"]

    # ------------------------------------------------------------------
    # LLM Provider
    # ------------------------------------------------------------------
    console.print("[bold]1. LLM Provider[/bold]")
    console.print("   Which provider do you want to use for generating llms.txt?\n")

    provider_choice = typer.prompt(
        "   Provider",
        default="gemini",
        prompt_suffix=" [gemini/claude/ambos]: ",
        show_default=False,
    ).strip().lower()

    while provider_choice not in ("gemini", "claude", "both"):
        console.print("   [red]Invalid option.[/red] Type gemini, claude, or both.")
        provider_choice = typer.prompt(
            "   Provider",
            default="gemini",
            prompt_suffix=" [gemini/claude/both]: ",
            show_default=False,
        ).strip().lower()

    # Normalize "ambos" → "both" for backwards compat from old wizard runs
    if provider_choice == "ambos":
        provider_choice = "both"

    console.print()

    if provider_choice in ("gemini", "both"):
        console.print("[bold]2. Gemini API Key[/bold]")
        console.print("   Get yours at: [link]https://aistudio.google.com/app/apikey[/link]\n")
        gemini_key = typer.prompt("   GEMINI_API_KEY", hide_input=True).strip()
        lines.append(f"\n# Google Gemini\nGEMINI_API_KEY={gemini_key}")
        console.print()

    if provider_choice in ("claude", "both"):
        console.print("[bold]3. Anthropic API Key[/bold]")
        console.print("   Get yours at: [link]https://console.anthropic.com/settings/keys[/link]\n")
        anthropic_key = typer.prompt("   ANTHROPIC_API_KEY", hide_input=True).strip()
        lines.append(f"\n# Anthropic Claude\nANTHROPIC_API_KEY={anthropic_key}")
        console.print()

    # ------------------------------------------------------------------
    # GitHub Token (optional)
    # ------------------------------------------------------------------
    next_num = 3 if provider_choice == "both" else 2
    console.print(f"[bold]{next_num + 1}. GitHub Token[/bold] [dim](optional — only needed for --github)[/dim]")
    console.print("   Used to read .md/.mdx files directly from a GitHub repository.")
    console.print("   Get yours at: [link]https://github.com/settings/tokens[/link] (scope: repo or public_repo)\n")

    use_github = typer.confirm("   Do you want to configure the GitHub token now?", default=True)

    if use_github:
        console.print()
        github_token = typer.prompt("   GITHUB_TOKEN", hide_input=True).strip()
        lines.append(f"\n# GitHub (required for --github)\nGITHUB_TOKEN={github_token}")

    console.print()

    # ------------------------------------------------------------------
    # Escreve o arquivo
    # ------------------------------------------------------------------
    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    console.print(Panel(
        f"[bold green]✅ .env criado com sucesso![/bold green]\n\n"
        f"  Localização: [cyan]{env_path}[/cyan]\n\n"
        f"  Próximo passo:\n"
        f"    [bold]prumo fetch <url-da-docs>[/bold]\n\n"
        f"  Com GitHub mode:\n"
        f"    [bold]prumo fetch <url-do-repo> --github[/bold]",
        expand=False,
    ))
    console.print()


# ---------------------------------------------------------------------------
# Command: prumo fetch
# ---------------------------------------------------------------------------


@app.command()
def fetch(
    url: Annotated[str, typer.Argument(help="Documentation URL or GitHub repository URL")],
    output: Annotated[
        str, typer.Option("--output", "-o", help="Output directory")
    ] = "./output",
    provider: Annotated[
        str,
        typer.Option("--provider", "-p", help="LLM provider: gemini or claude"),
    ] = "gemini",
    api_key: Annotated[
        str | None,
        typer.Option("--api-key", "-k", help="API key for the LLM provider"),
    ] = None,
    max_pages: Annotated[
        int,
        typer.Option("--max-pages", "-m", help="Maximum number of pages/files to process"),
    ] = 50,
    github: Annotated[
        bool,
        typer.Option(
            "--github",
            help=(
                "Use GitHub Contents API to read .md/.mdx from the repository. "
                "Ideal for sites with a JS-Wall (Docusaurus, VitePress, Next.js). "
                "Requires GITHUB_TOKEN or --github-token."
            ),
        ),
    ] = False,
    github_token: Annotated[
        str | None,
        typer.Option("--github-token", help="GitHub Personal Access Token"),
    ] = None,
    docs_base_url: Annotated[
        str | None,
        typer.Option(
            "--docs-base-url",
            "-d",
            help=(
                "Base URL of the published documentation. When provided, links in "
                "llms.txt will point to the docs site instead of GitHub source. "
                "Example: --docs-base-url https://developers.stellar.org/docs"
            ),
        ),
    ] = None,
) -> None:
    """Fetch documentation and generate an llms.txt file for AI agents."""
    if provider not in ("gemini", "claude"):
        console.print(
            f"[bold red]Error:[/] Invalid provider: '{provider}'. "
            "Use 'gemini' or 'claude'."
        )
        raise typer.Exit(code=1)

    resolved_key = _resolve_api_key(provider, api_key)

    # -----------------------------------------------------------------------
    # GitHub mode
    # -----------------------------------------------------------------------
    if github:
        resolved_github_token = _resolve_github_token(github_token)

        console.print(f"\n[bold]🐙 GitHub mode:[/] [cyan]{url}[/cyan]")
        if docs_base_url:
            console.print(f"   [dim]Links will point to:[/dim] [cyan]{docs_base_url}[/cyan]")
        console.print()

        with Progress(
            SpinnerColumn(),
            TextColumn("[bold cyan]{task.description}"),
            BarColumn(bar_width=30),
            TaskProgressColumn(),
            TextColumn("[dim]{task.fields[filename]}"),
            console=console,
            transient=False,
        ) as progress:
            task = progress.add_task("Collecting files...", total=max_pages, filename="")

            def on_progress(count: int, name: str) -> None:
                progress.update(task, completed=count, filename=name)

            pages = crawl_github(
                url,
                resolved_github_token,
                max_pages=max_pages,
                docs_base_url=docs_base_url,
                on_progress=on_progress,
            )
            progress.update(task, completed=len(pages), filename="")

        if not pages:
            console.print(
                "\n[bold yellow]Warning:[/] No .md/.mdx files found in the repository.\n"
                "  Check that the URL points to a valid GitHub repository and that the\n"
                "  GITHUB_TOKEN has read access. Run [bold]prumo init[/bold] to reconfigure."
            )
            raise typer.Exit(code=1)

        console.print(f"\n  ✅ {len(pages)} arquivos encontrados\n")

    # -----------------------------------------------------------------------
    # Default static HTTP mode
    # -----------------------------------------------------------------------
    else:
        console.print(f"\n[bold]🔍 Validating URL:[/] {url}")
        _validate_url(url)

        console.print(f"[bold]🕷️  Crawling [cyan]{url}[/cyan]...[/]")
        
        with Progress(
            SpinnerColumn(),
            TextColumn("[bold cyan]{task.description}"),
            BarColumn(bar_width=30),
            TaskProgressColumn(),
            TextColumn("[dim]{task.fields[filename]}"),
            console=console,
            transient=False,
        ) as progress:
            task = progress.add_task("Crawling pages...", total=max_pages, filename="")

            def on_progress(count: int, name: str) -> None:
                progress.update(task, completed=count, filename=name)

            pages = crawl(
                url, 
                max_pages=max_pages, 
                on_progress=on_progress
            )
            progress.update(task, completed=len(pages), filename="")

        if not pages:
            console.print(
                "\n[bold yellow]Aviso:[/] Nenhuma página encontrada.\n"
                "  [dim]Dica: se o site usa JavaScript para renderizar o conteúdo "
                "(Docusaurus, VitePress, Next.js), use a flag [bold]--github[/bold] "
                "com a URL do repositório da documentação.[/dim]"
            )
            raise typer.Exit(code=1)

        console.print(f"\n  ✅ {len(pages)} páginas processadas\n")

    # -----------------------------------------------------------------------
    # Export — same for both modes
    # -----------------------------------------------------------------------
    console.print(f"[bold]📝 Exporting to llms.txt via [cyan]{provider}[/cyan]...[/]")
    result = export_llms_txt(pages, provider, resolved_key)  # type: ignore[arg-type]

    output_dir = Path(output)
    output_dir.mkdir(parents=True, exist_ok=True)
    output_file = output_dir / "llms.txt"
    output_file.write_text(result, encoding="utf-8")

    console.print(
        f"\n[bold green]✅ Done![/] llms.txt written to [cyan]{output_file}[/cyan]\n"
    )


if __name__ == "__main__":
    app()